# For puppetlabs_spec_helper documentation - see http://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    jenkins: 'https://github.com/jenkinsci/puppet-jenkins.git'
  symlinks:
    jenkins_server/files: '../../../../files'
    jenkins_server/manifests: '../../../../manifests'
    jenkins_server/templates: '../../../../templates'
