VAGRANT_GEMFILE = __FILE__ unless defined? VAGRANT_GEMFILE

source 'http://rubygems.org'

gem 'rake', '< 11'
gem 'colorize'

gem 'puppet', '~> 3.7.1'

gem 'rspec', '~> 3.1.0'
gem 'puppet-lint', '~> 1.1.0'
gem 'rspec-puppet', '~> 1.0.1'
gem 'puppetlabs_spec_helper', '~> 0.8.2'
gem 'serverspec', '~> 2.6.0'

Dir["#{File.dirname(VAGRANT_GEMFILE)}/bundler.d/*.rb"].each do |bundle|
  self.instance_eval(Bundler.read_file(bundle))
end
