# For puppetlabs_spec_helper documentation - see http://github.com/puppetlabs/puppetlabs_spec_helper

fixtures:
  repositories:
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib'
    epel: 'https://github.com/stahnma/puppet-module-epel.git'
    java: 'https://github.com/puppetlabs/puppetlabs-java.git'
  symlinks:
    java_me/files: '../../../../files'
    java_me/manifests: '../../../../manifests'
    java_me/templates: '../../../../templates'
