# http://api.rubyonrails.org/v2.3.8/classes/Fixtures.html
fixtures:
  repositories:
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    files/files: '../../../../files'
    files/manifests: '../../../../manifests'
    files/templates: '../../../../templates'
